In [4]:
import torch

A Tensor is just like an Multi Dimensional Array

In [5]:
x = torch.Tensor([5,3])
y = torch.Tensor([2,1])

print(x*y)

tensor([10.,  3.])


PyTorch provides similar utilities as NumPy

In [7]:
# zeroes
x = torch.zeros([2,5])

In [8]:
print(x)

tensor([[0., 0., 0., 0., 0.],
        [0., 0., 0., 0., 0.]])


In [9]:
x.shape

torch.Size([2, 5])

In [12]:
# random initialisation of a 2 by 5 tensor
y = torch.rand([2,5])

In [13]:
print(y)

tensor([[0.5992, 0.0916, 0.4201, 0.1827, 0.8531],
        [0.4471, 0.0977, 0.3319, 0.2019, 0.2093]])


Reshaping in PyTorch uses a method called ```view([])```, the NumPy equivelant is just ```.reshape([])```. Note that ```view([])``` is not 'inplace' so you will need to reassign.

In [15]:
# for example to flatten a 2 by 5, would be to make the Tensor a 1 by 10
y = y.view([1,10])

In [18]:
print(y.shape)
print(y)

torch.Size([1, 10])
tensor([[0.5992, 0.0916, 0.4201, 0.1827, 0.8531, 0.4471, 0.0977, 0.3319, 0.2019,
         0.2093]])
