In [1]:
import torch

A Tensor is just like an Multi Dimensional Array

In [2]:
x = torch.Tensor([5,3])
y = torch.Tensor([2,1])

print(x*y)

tensor([10.,  3.])


PyTorch provides similar utilities as NumPy

In [3]:
# zeroes
x = torch.zeros([2,5])

In [4]:
print(x)

tensor([[0., 0., 0., 0., 0.],
        [0., 0., 0., 0., 0.]])


In [5]:
x.shape

torch.Size([2, 5])

In [6]:
# random initialisation of a 2 by 5 tensor
y = torch.rand([2,5])

In [7]:
print(y)

tensor([[0.9786, 0.7192, 0.9691, 0.8034, 0.5165],
        [0.1344, 0.5148, 0.5002, 0.3053, 0.5539]])


Reshaping in PyTorch uses a method called ```view([])```, the NumPy equivelant is just ```.reshape([])```. Note that ```view([])``` is not 'inplace' so you will need to reassign.

In [8]:
# for example to flatten a 2 by 5, would be to make the Tensor a 1 by 10
y = y.view([1,10])

In [9]:
print(y.shape)
print(y)

torch.Size([1, 10])
tensor([[0.9786, 0.7192, 0.9691, 0.8034, 0.5165, 0.1344, 0.5148, 0.5002, 0.3053,
         0.5539]])
